3414894965 base subscription events
LykaAnalytics/dbt-lyka pull request #17
Opened 2022-11-08 02:46 UTC by agpmercado

Hey Oscar, 

Raising my Pull Request although I know there may be a number of changes for Access layer objects that I want to discuss further with you during Office Hours tomorrow.

2022-11-09 07:33 UTC, lukersmithoscar requested changes
Hey @agpmercado, great start, its a tonne of work! 
Lets book a session to run over the feedback, it will be easier in person.
I am super excited because now is the time I get to show you the **exciting** part of dbt and how it will help you.

2022-11-09 07:33 UTC, lukersmithoscar commented on models/access/dim/dim_product.sql
> +    sum(case when ao.add_on_id = 1 then 1 else 0 end) as welcome_pack,
hey @agpmercado, let's talk about these case statements.

2022-11-09 07:33 UTC, lukersmithoscar commented on models/access/fact/base/base_user_subscription_event.sql
> +
We can refactor this as well

2022-11-09 07:33 UTC, lukersmithoscar commented on models/staging/portal/stg_portal_add_on.sql
> +        barcodes as barcode,
doesn't conform to our naming standard

2022-11-09 07:33 UTC, lukersmithoscar commented on models/staging/portal/stg_portal_order_inventory.sql
> +        end as is_override_flag
naming standard

2022-11-09 07:33 UTC, lukersmithoscar commented on models/staging/portal/stg_portal_order_inventory.sql
> +        total_turkey_override,
naming standard

2022-11-09 07:33 UTC, lukersmithoscar commented on models/staging/portal/stg_portal_order_inventory.sql
> +        total_beef_override,
naming standard

2022-11-09 07:33 UTC, lukersmithoscar commented on models/staging/portal/stg_portal_order_inventory.sql
> +        daily_grams_override,
naming standard

2022-11-09 07:33 UTC, lukersmithoscar commented on models/staging/portal/stg_portal_product.sql
> +        sku_size,
what is this? naming standard

2022-11-09 22:08 UTC, agpmercado commented
> 

Hey @lukersmithoscar , thanks for reviewing them! Although please note this was raised before our Office Session yesterday so I know a bunch of stuff will change in the Access layers part. I'll revise the comments on the staging layers then set-up a session as you have suggested. Excited to learn more about it as well! :)

2022-11-10 03:18 UTC, agpmercado commented on models/staging/portal/stg_portal_order_inventory.sql
> +        daily_grams_override,
I have renamed this in final select statement! should we also alias it in CTEs?

2022-11-15 03:46 UTC, agpmercado commented on models/access/dim/dim_product.sql
> +    sum(case when ao.add_on_id = 1 then 1 else 0 end) as welcome_pack,
I have deleted these for now as this is for another data model & since we're not doing dimensions atm

2022-11-18 00:41 UTC, lukersmithoscar approved these changes

2022-11-18 00:41 UTC, merged